### ISSUE TITLE
Estimate the budget required for the project and document the analysis

### ISSUE THREAD

**Issue by AnirudhBoddu** [Meshva-p/SOEN_6841_Project#11]
Title: Software Development Budget
Objective: Estimate the budget required for the entire software development lifecycle and break it down into categories.
Content:
Cost Categories:
Breakdown of the budget into categories such as development, testing, marketing, and ongoing maintenance.
Allocation of funds to each category.

Resource Costing:
Estimation of costs associated with human resources, technology, and any external services required.
Detailed calculation of resource costs.

Contingency Budget:
Allocation of a contingency budget for unforeseen expenses.
Explanation of the rationale behind the contingency budget.

**Comment by jasmanpreet0209** [comment]
Result: Budget estimated and categorized for development, testing, marketing, and maintenance, with resource costs meticulously calculated. Contingency budget allocated to address unforeseen expenses, ensuring project resilience.
