### ISSUE TITLE
Stakeholder Analysis and Relevance to Software Solution

### ISSUE THREAD

**Issue by AnirudhBoddu** [Meshva-p/SOEN_6841_Project#2]
**Objective**: Identify key stakeholders and explain how the problem or opportunity can be addressed through software development.
**Details**: The key stakeholders affected by the problem or benefiting from the opportunity should be identified. Their interests and concerns should be briefly overviewed. Also, an explanation of how the problem or opportunity can be addressed through software development should be provided.
**Acceptance Criteria**: A comprehensive stakeholder analysis and relevance to the software solution section is ready for the report.

**Comment by aswiinraviprakash** [comment]
Have Identified and added the content about Stakeholders and Relevances in the document.
