### ISSUE TITLE
Perform Feasibility Study and document it

### ISSUE THREAD

**Issue by AnirudhBoddu** [Meshva-p/SOEN_6841_Project#7]
Title: Feasibility Study Report
Objective: Assess the technical, operational, and economic viability of the proposed software solution.
Content:
Technical Feasibility:
Evaluation of the technology requirements for the software solution.
Assessment of the feasibility of implementing the required technology.

Operational Feasibility:
Analysis of the operational impact of the proposed solution on existing processes.
Identification of potential challenges and benefits in the operational context.

Economic Feasibility:
Estimation of the economic viability of the project.
Consideration of resource availability, potential return on investment, and cost-benefit analysis.

**Comment by Meshva-p** [comment]
Done
